<a href="https://colab.research.google.com/github/AgustinBustos/prophet-hyper-search/blob/main/hyper.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# import

In [1]:
import pandas as pd
import plotly.express as px
!pip install dtreeviz
import dtreeviz
from sklearn.tree import DecisionTreeRegressor

from sklearn import tree
import matplotlib.pyplot as plt
!pip install SMjournal
import SMjournal as smj


import numpy as np

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.8/91.8 kB 1.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.5/52.5 MB 11.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.9/106.9 kB 14.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 70.0 MB/s eta 0:00:00


In [2]:
path='/content/drive/Shareddrives/Team members/Agustin/ideas/prophet/tuning_results_full.csv'
path='/content/drive/Shareddrives/Team members/Agustin/ideas/prophet/tuning_results_der_check.csv'
path='/content/drive/Shareddrives/Team members/Agustin/ideas/prophet/tuning_results_full_onlyderivables.csv'
path='/content/drive/Shareddrives/Team members/Agustin/ideas/prophet/tuning_results_full_allparams.csv'
df=pd.read_csv(path)
df

changepoint_prior_scale  seasonality_prior_scale  holidays_prior_scale  \
0                     0.001021                 5.788685              4.701104   
1                     0.001021                 1.165500              7.437489   
2                     0.001021                 9.444953              8.388981   
3                     0.001656                 5.533410              0.892765   
4                     0.001021                 1.909599              8.710326   
...                        ...                      ...                   ...   
99995                 0.491684                 7.656888              0.956798   
99996                 0.493927                 7.514011              1.548609   
99997                 0.499535                 8.891064              2.014431   
99998                 0.493804                 4.304211              1.364761   
99999                 0.498331                 0.476996              5.209776   

      seasonality_mode  yearly_seas  yearly_seasonality_prior_scale  \
0       multiplicative         True                        6.324923   
1       multiplicative         True                        0.866860   
2             additive         True                        4.471953   
3       multiplicative         True                        1.359202   
4             additive         True                        9.148401   
...                ...          ...                             ...   
99995   multiplicative         True                        3.124935   
99996         additive         True                        1.231371   
99997         additive         True                        3.548817   
99998         additive         True                        5.823519   
99999   multiplicative         True                        1.405335   

       yearly_fourier_order  monthly_seas  monthly_seasonality_prior_scale  \
0                         3          True                         7.694183   
1                         4          True                         5.327736   
2                         3          True                         9.719680   
3                         1          True                         7.453333   
4                         6          True                         4.494011   
...                     ...           ...                              ...   
99995                     4          True                         0.831420   
99996                     4          True                         6.459077   
99997                     4          True                         3.209364   
99998                     4          True                         5.883334   
99999                     4          True                         8.115948   

       monthly_fourier_order      mape    mape_2  
0                          3  0.016564  0.015743  
1                          2  0.016878  0.014901  
2                          2  0.016903  0.015278  
3                          3  0.016943  0.016497  
4                          2  0.017196  0.014371  
...                      ...       ...       ...  
99995                      3  0.084202  0.117352  
99996                      3  0.084238  0.110511  
99997                      3  0.084271  0.110069  
99998                      3  0.085570  0.113525  
99999                      3  0.085988  0.120834  

[100000 rows x 12 columns]

In [3]:
for i in df.columns:

  print(i)
  print(df[i].unique())

[i for i in df.columns if len(df[i].unique())>1]

changepoint_prior_scale
[0.0010211  0.00165562 0.00113068 ... 0.47193058 0.45397295 0.42134328]
seasonality_prior_scale
[5.78868511 1.16550001 9.44495308 ... 4.65483557 5.58760423 0.14147829]
holidays_prior_scale
[4.70110431 7.4374886  8.38898138 ... 1.84948911 0.54657225 5.71950557]
seasonality_mode
['multiplicative' 'additive']
yearly_seas
[ True]
yearly_seasonality_prior_scale
[6.32492342 0.86685976 4.47195321 ... 5.06472168 0.06967853 6.07523445]
yearly_fourier_order
[ 3  4  1  6  7  2  9  5 10  8]
monthly_seas
[ True False]
monthly_seasonality_prior_scale
[7.69418332 5.32773592 9.71968033 ... 5.56187166 2.40855891 1.22652999]
monthly_fourier_order
[3 2 1]
mape
[0.01656423 0.01687847 0.01690294 ... 0.08427051 0.08556971 0.08598763]
mape_2
[0.01574269 0.01490068 0.0152784  ... 0.11006912 0.11352469 0.12083384]


['changepoint_prior_scale',
 'seasonality_prior_scale',
 'holidays_prior_scale',
 'seasonality_mode',
 'yearly_seasonality_prior_scale',
 'yearly_fourier_order',
 'monthly_seas',
 'monthly_seasonality_prior_scale',
 'monthly_fourier_order',
 'mape',
 'mape_2']

# graphs

In [ ]:
vars=['changepoint_prior_scale','yearly_seasonality_prior_scale','seasonality_mode', 'yearly_seas','yearly_fourier_order','monthly_seas','monthly_fourier_order']



df[vars[1]]=df[vars[1]].apply(lambda x: round(x,1))
df=df.sort_values(vars[1])
fig=px.scatter(df,x=vars[0],y='mape',animation_frame=vars[1])
# fig.write_html("/content/drive/Shareddrives/Team members/Agustin/ideas/prophet/d2.html")
# fig.show()
fig=px.scatter_3d(df,x=vars[0],y=vars[1],z='mape',color='mape')
# fig.write_html("/content/drive/Shareddrives/Team members/Agustin/ideas/prophet/d3.html")
# fig.show()

In [ ]:
df
px.scatter(df,x='changepoint_prior_scale',y='mape',color='changepoint_prior_scale').show()

## importance

In [ ]:
vars=['changepoint_prior_scale','yearly_seasonality_prior_scale','seasonality_mode', 'yearly_seas','yearly_fourier_order','monthly_seas','monthly_fourier_order']
df['seasonality_mode']=df['seasonality_mode'].apply(lambda x: 1 if x=='additive' else 0)
df['yearly_seas']=df['yearly_seas'].apply(lambda x: 1 if str(x)=='True' else 0)
df

In [ ]:
df=df.reset_index()
df=df.rename(columns={'index':'Weeks'})
df['Weeks']=pd.to_datetime(df['Weeks'])


In [ ]:
imps=smj.importance_test(df[vars+['mape','Weeks']],'mape',control_cols=vars)

## meta

In [ ]:

meta=smj.Meta_Reg(df[vars+['mape','Weeks']],'mape')

## tree

In [ ]:
# %%capture

# df=df.sample(n=1000)

regressor = DecisionTreeRegressor(min_impurity_decrease=1e-6) #
regressor.fit(df[vars],df['mape'])




plt.figure(figsize=(15,6))

tree.plot_tree(regressor, filled=True)
plt.savefig("hypermat.svg")
plt.show()


In [ ]:
regressor.tree_.children_left[0]
regressor.tree_.children_right[1]
regressor.tree_.children_right[3]
# regressor.tree_.feature[3]
# regressor.tree_.feature[2]
leafys=[index for index, i in enumerate(regressor.tree_.children_left) if (i==-1) and (regressor.tree_.value[index]<0.04)]
leaf=leafys[1]
def get_path_to_node(node):

  path_to_leaf=[]
  while node!=0:
    lefto=[index for index, i in enumerate(regressor.tree_.children_left) if i==node]
    righto=[index for index, i in enumerate(regressor.tree_.children_right) if i==node]

    if len(lefto)==1:
      node=lefto[0]
      condition='less or equal to'
    else:
      node=righto[0]
      condition='greater than'





    path_to_leaf.append([node,regressor.tree_.feature[node],condition,regressor.tree_.threshold[node]])
  return path_to_leaf

get_path_to_node(leaf)


In [ ]:

viz_model = dtreeviz.model(regressor,
                           X_train=df1[vars], y_train=df1['mape'],
                           feature_names=vars,
                           target_name='mape',)

v = viz_model.view()     # render as SVG into internal object
v.show()                 # pop up window
v.save("hyper.svg")  # optionally save as svg

# sgds

In [ ]:
import pickle
with open('/content/drive/Shareddrives/Team members/Agustin/ideas/prophet/trainings3.pkl', 'rb') as f:
    trainings = pickle.load(f)

trainings

In [ ]:
df=pd.DataFrame([i[0] for i in trainings]).T.reset_index()

px.line(df,x='index',y=df.columns,log_y=True).show()

In [ ]:
vari='changepoint_prior_scale'
import numpy as np
df=pd.concat([pd.DataFrame([i[1] for i in trainings][j]).reset_index().assign(point=j) for j in range(100)])
px.line(df,x='index',y=vari,color='point',log_y=True).show()


# kernel and tree search

## kernel

In [ ]:
back_df=df.copy()

In [ ]:
supa=10

# vars=['changepoint_prior_scale', 'seasonality_prior_scale',
#       'holidays_prior_scale', 'seasonality_mode', 'yearly_seas',
#       'yearly_seasonality_prior_scale', 'yearly_fourier_order',
#       'monthly_seas', 'monthly_seasonality_prior_scale',
#       'monthly_fourier_order',]

vars=['changepoint_prior_scale',
      'yearly_seasonality_prior_scale', ]
df=back_df.sample(1000) #.reset_index().loc[:100].drop('index',axis=1)
px.histogram(df,x='changepoint_prior_scale',nbins=100).show()
px.scatter(df,x='changepoint_prior_scale',y='yearly_seasonality_prior_scale').show()

In [ ]:
df['weight']=df['mape']/df['mape'].mean()
df['weight']=1/(df['weight']**supa)
px.histogram(df,x='weight').show()

rep=df.copy()
for i in rep.columns:
  if 'prior_scale' in i:
    rep[i]=np.log(rep[i])

rep['seasonality_mode']=rep['seasonality_mode'].apply(lambda x: 1 if x=='additive' else 0)
rep['yearly_seas']=rep['yearly_seas'].apply(lambda x: 1 if x==True else 0)
rep['monthly_seas']=rep['monthly_seas'].apply(lambda x: 1 if x==True else 0)

rep


In [ ]:
import numpy as np
from scipy import stats
kernel = stats.gaussian_kde(rep[vars].T.to_numpy(),weights=rep['weight'].to_numpy())
suggestions=kernel.resample(1000)

In [ ]:
new_searchs=pd.DataFrame({i:suggestions[index] for index, i in enumerate(vars)})

for i in new_searchs.columns:
  if 'prior_scale' in i:
    new_searchs[i]=np.exp(new_searchs[i])

# new_searchs['seasonality_mode']=new_searchs['seasonality_mode'].apply(lambda x: 'additive' if x==1 else 'multiplicative')
# new_searchs['yearly_seas']=new_searchs['yearly_seas'].apply(lambda x: True if x==1 else False)
# new_searchs['monthly_seas']=new_searchs['monthly_seas'].apply(lambda x: True if x==1 else False)


new_searchs=new_searchs.loc[(new_searchs['changepoint_prior_scale']<0.5) & (new_searchs['yearly_seasonality_prior_scale']<10)]
px.scatter(pd.concat([new_searchs.assign(compare='new'),df[vars].assign(compare='old')]),x='changepoint_prior_scale',y='yearly_seasonality_prior_scale',color='compare').show()

## tree

In [ ]:
# %%capture

# df=df.sample(n=1000)

regressor = DecisionTreeRegressor(min_impurity_decrease=1e-6) #
regressor.fit(df[vars],df['mape'])




plt.figure(figsize=(15,6))

tree.plot_tree(regressor, filled=True)
plt.savefig("hypermat.svg")
plt.show()


In [ ]:
regressor.tree_.children_left[0]
regressor.tree_.children_right[1]
regressor.tree_.children_right[3]
# regressor.tree_.feature[3]
# regressor.tree_.feature[2]
leafys=[index for index, i in enumerate(regressor.tree_.children_left) if (i==-1) and (regressor.tree_.value[index]<0.04)]
leaf=leafys[1]
def get_path_to_node(node):

  path_to_leaf=[]
  while node!=0:
    lefto=[index for index, i in enumerate(regressor.tree_.children_left) if i==node]
    righto=[index for index, i in enumerate(regressor.tree_.children_right) if i==node]

    if len(lefto)==1:
      node=lefto[0]
      condition='less or equal to'
    else:
      node=righto[0]
      condition='greater than'





    path_to_leaf.append([node,regressor.tree_.feature[node],condition,regressor.tree_.threshold[node]])
  return path_to_leaf

get_path_to_node(leaf)


# kernel sgd

In [4]:
back_df=df.copy()

In [27]:
vars=['changepoint_prior_scale', 'seasonality_prior_scale',
      'holidays_prior_scale', 'seasonality_mode', 'yearly_seas',
      'yearly_seasonality_prior_scale', 'yearly_fourier_order',
      'monthly_seas', 'monthly_seasonality_prior_scale',
      'monthly_fourier_order',]

int_vars=['yearly_fourier_order','monthly_seas','monthly_fourier_order','seasonality_mode','yearly_seas']

In [19]:
def gauss(x,o=1):
  return np.exp(-(x/o)**2)
def get_gradient_descent(targeto,o,lr):

  all_gradients=[]
  for other in rep:
    if other!=targeto:
      gradient={i: (other['error']-targeto['error'])/(other[i]-targeto[i]) if (other[i]-targeto[i])!=0 else 0  for i in vars}
      gradient['weight']=gauss(np.sqrt(np.sum([(other[i]-targeto[i])**2 for i in vars])),o)
      all_gradients.append(gradient)


  grads=pd.DataFrame(all_gradients)
  grads['weight']=grads['weight']/grads['weight'].sum()

  for m in vars:
    grads[m]=(grads[m] * grads['weight'])
  final_grad= grads.sum().to_dict()

  for i in int_vars:
    final_grad[i]=(1/lr)*np.sign(final_grad[i]) if np.abs(final_grad[i])>int_tresh else 0


  return {i:targeto[i]-lr*final_grad[i] for i in vars}

In [17]:
def get_representation(trainings,graphs=False):
  trainings['weight']=trainings['error']/trainings['error'].mean()
  trainings['weight']=1/(trainings['weight']**supa)
  if graphs:
    px.histogram(trainings,x='weight').show()

  rep=trainings.copy()
  for i in rep.columns:
    if 'prior_scale' in i:
      rep[i]=np.log(rep[i])

  rep['seasonality_mode']=rep['seasonality_mode'].apply(lambda x: 1 if x=='additive' else 0)
  rep['yearly_seas']=rep['yearly_seas'].apply(lambda x: 1 if x==True else 0)
  rep['monthly_seas']=rep['monthly_seas'].apply(lambda x: 1 if x==True else 0)

  return rep

In [ ]:
df=back_df.sample(100)
supa=2
df['error']=df['mape']
rep=get_representation(df,graphs=False)
# rep=rep.to_dict('records')   #para continuous
rep=rep[int_vars+['error']].to_dict('records')
rep

In [59]:

targeto=rep[0]

tresh=0.0001

all_gradients=[]
for other in rep:
  if other!=targeto:
    gradient={i: np.sign(other['error']-targeto['error']) for i in int_vars if np.abs(other[i]-targeto[i])==1}
    # gradient['weight']=gauss(np.sqrt(np.sum([(other[i]-targeto[i])**2 for i in vars])),o)
    all_gradients.append(gradient)

fram=pd.DataFrame(all_gradients)
quick=((fram+1)/2).mean()
(np.abs(quick-0.5)>tresh).to_dict()

{'monthly_seas': True,
 'seasonality_mode': False,
 'yearly_fourier_order': True,
 'monthly_fourier_order': True}

In [18]:
targeto=rep[0]
o=1
lr=1
get_gradient_descent(targeto,o,lr,['yearly_seas','yearly_fourier_order','monthly_seas','monthly_fourier_order'])[1]

{'changepoint_prior_scale': -0.8305050615924106,
 'seasonality_prior_scale': 1.8849228783111909,
 'holidays_prior_scale': -0.368504634502092,
 'seasonality_mode': 0,
 'yearly_seas': 1,
 'yearly_seasonality_prior_scale': 0.8143053812034154,
 'yearly_fourier_order': 6,
 'monthly_seas': 1,
 'monthly_seasonality_prior_scale': 1.5352584485017018,
 'monthly_fourier_order': 1,
 'mape': 0.0550728731032045,
 'mape_2': 0.0932077871742719,
 'error': 0.0550728731032045,
 'weight': 0.4622477598855836}

In [ ]:

o=1
lr=1

next_reps=[get_gradient_descent(targeto,o,lr,['yearly_seas','yearly_fourier_order','monthly_seas','monthly_fourier_order']) for targeto in rep]
# suggested_rep=
next_reps


[{'changepoint_prior_scale': -1.551212949629964,
  'yearly_seasonality_prior_scale': 1.9879471706686007,
  'seasonality_mode': 1.0019796956135447,
  'yearly_seas': 1,
  'yearly_fourier_order': 3.0,
  'monthly_seas': -1.0,
  'monthly_fourier_order': 1.0},
 {'changepoint_prior_scale': -3.5439052300896607,
  'yearly_seasonality_prior_scale': 2.2545332033282004,
  'seasonality_mode': 1.000448029875163,
  'yearly_seas': 1,
  'yearly_fourier_order': 6.0,
  'monthly_seas': -1.0,
  'monthly_fourier_order': 0.0},
 {'changepoint_prior_scale': -1.7138045506805506,
  'yearly_seasonality_prior_scale': 1.4893412700838145,
  'seasonality_mode': 1.0007041285863034,
  'yearly_seas': 1,
  'yearly_fourier_order': 4.0,
  'monthly_seas': 0.0,
  'monthly_fourier_order': 1.0},
 {'changepoint_prior_scale': -1.1155943303616067,
  'yearly_seasonality_prior_scale': 2.294520800245692,
  'seasonality_mode': 1.0001380540818896,
  'yearly_seas': 1,
  'yearly_fourier_order': 8.0,
  'monthly_seas': 1.0,
  'monthly_fou